#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-online-accounts
Version  : 3.21.4
Release  : 1
URL      : https://download.gnome.org/core/3.21/3.21.4/sources/gnome-online-accounts-3.21.4.tar.xz
Source0  : https://download.gnome.org/core/3.21/3.21.4/sources/gnome-online-accounts-3.21.4.tar.xz
Summary  : GNOME Online Accounts Library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: gnome-online-accounts-lib
Requires: gnome-online-accounts-data
Requires: gnome-online-accounts-locales
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : krb5-dev
BuildRequires : libc-bin
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gcr-3)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libxml-2.0)

%description
GNOME Online Accounts - Single sign-on framework for GNOME
==========================================================

%package data
Summary: data components for the gnome-online-accounts package.
Group: Data

%description data
data components for the gnome-online-accounts package.


%package dev
Summary: dev components for the gnome-online-accounts package.
Group: Development
Requires: gnome-online-accounts-lib
Requires: gnome-online-accounts-data
Provides: gnome-online-accounts-devel

%description dev
dev components for the gnome-online-accounts package.


%package lib
Summary: lib components for the gnome-online-accounts package.
Group: Libraries
Requires: gnome-online-accounts-data

%description lib
lib components for the gnome-online-accounts package.


%package locales
Summary: locales components for the gnome-online-accounts package.
Group: Default

%description locales
locales components for the gnome-online-accounts package.


%prep
%setup -q -n gnome-online-accounts-3.21.4

%build
export LANG=C
%configure --disable-static --disable-inspector --disable-backend
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang gnome-online-accounts

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/services/org.gnome.OnlineAccounts.service
/usr/share/gir-1.0/Goa-1.0.gir
/usr/share/icons/hicolor/16x16/apps/goa-account-facebook.png
/usr/share/icons/hicolor/16x16/apps/goa-account-flickr.png
/usr/share/icons/hicolor/16x16/apps/goa-account-foursquare.png
/usr/share/icons/hicolor/16x16/apps/goa-account-google.png
/usr/share/icons/hicolor/16x16/apps/goa-account-msn.png
/usr/share/icons/hicolor/16x16/apps/goa-account-owncloud.png
/usr/share/icons/hicolor/16x16/apps/goa-account-pocket.png
/usr/share/icons/hicolor/16x16/apps/goa-account.png
/usr/share/icons/hicolor/22x22/apps/goa-account-facebook.png
/usr/share/icons/hicolor/22x22/apps/goa-account-flickr.png
/usr/share/icons/hicolor/22x22/apps/goa-account-foursquare.png
/usr/share/icons/hicolor/22x22/apps/goa-account-google.png
/usr/share/icons/hicolor/22x22/apps/goa-account-msn.png
/usr/share/icons/hicolor/22x22/apps/goa-account-owncloud.png
/usr/share/icons/hicolor/22x22/apps/goa-account-pocket.png
/usr/share/icons/hicolor/22x22/apps/goa-account.png
/usr/share/icons/hicolor/24x24/apps/goa-account-facebook.png
/usr/share/icons/hicolor/24x24/apps/goa-account-flickr.png
/usr/share/icons/hicolor/24x24/apps/goa-account-foursquare.png
/usr/share/icons/hicolor/24x24/apps/goa-account-google.png
/usr/share/icons/hicolor/24x24/apps/goa-account-msn.png
/usr/share/icons/hicolor/24x24/apps/goa-account-owncloud.png
/usr/share/icons/hicolor/24x24/apps/goa-account-pocket.png
/usr/share/icons/hicolor/24x24/apps/goa-account.png
/usr/share/icons/hicolor/256x256/apps/goa-account.png
/usr/share/icons/hicolor/32x32/apps/goa-account-facebook.png
/usr/share/icons/hicolor/32x32/apps/goa-account-flickr.png
/usr/share/icons/hicolor/32x32/apps/goa-account-foursquare.png
/usr/share/icons/hicolor/32x32/apps/goa-account-google.png
/usr/share/icons/hicolor/32x32/apps/goa-account-msn.png
/usr/share/icons/hicolor/32x32/apps/goa-account-owncloud.png
/usr/share/icons/hicolor/32x32/apps/goa-account-pocket.png
/usr/share/icons/hicolor/32x32/apps/goa-account.png
/usr/share/icons/hicolor/48x48/apps/goa-account-facebook.png
/usr/share/icons/hicolor/48x48/apps/goa-account-flickr.png
/usr/share/icons/hicolor/48x48/apps/goa-account-foursquare.png
/usr/share/icons/hicolor/48x48/apps/goa-account-google.png
/usr/share/icons/hicolor/48x48/apps/goa-account-msn.png
/usr/share/icons/hicolor/48x48/apps/goa-account-owncloud.png
/usr/share/icons/hicolor/48x48/apps/goa-account-pocket.png
/usr/share/icons/hicolor/48x48/apps/goa-account.png
/usr/share/icons/hicolor/96x96/apps/goa-account-facebook.png
/usr/share/icons/hicolor/96x96/apps/goa-account-flickr.png
/usr/share/icons/hicolor/96x96/apps/goa-account-foursquare.png
/usr/share/icons/hicolor/96x96/apps/goa-account-google.png
/usr/share/icons/hicolor/96x96/apps/goa-account-msn.png
/usr/share/icons/hicolor/96x96/apps/goa-account-owncloud.png
/usr/share/icons/hicolor/96x96/apps/goa-account-pocket.png
/usr/share/icons/hicolor/96x96/apps/goa-account.png

%files dev
%defattr(-,root,root,-)
/usr/include/goa-1.0/goa/goa-generated.h
/usr/include/goa-1.0/goa/goa.h
/usr/include/goa-1.0/goa/goaclient.h
/usr/include/goa-1.0/goa/goaenums.h
/usr/include/goa-1.0/goa/goaenumtypes.h
/usr/include/goa-1.0/goa/goaerror.h
/usr/include/goa-1.0/goa/goatypes.h
/usr/include/goa-1.0/goa/goaversion.h
/usr/lib64/*.so
/usr/lib64/girepository-1.0/Goa-1.0.typelib
/usr/lib64/goa-1.0/include/goaconfig.h
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f gnome-online-accounts.lang 
%defattr(-,root,root,-)

