#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-online-accounts
Version  : 3.46.0
Release  : 47
URL      : https://download.gnome.org/sources/gnome-online-accounts/3.46/gnome-online-accounts-3.46.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-online-accounts/3.46/gnome-online-accounts-3.46.0.tar.xz
Summary  : Backends for GNOME Online Accounts Library
Group    : Development/Tools
License  : LGPL-2.0
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : json-glib-dev
BuildRequires : krb5-dev
BuildRequires : libc-bin
BuildRequires : pkgconfig(gcr-3)
BuildRequires : pkgconfig(javascriptcoregtk-4.1)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(rest-1.0)

%description
GNOME Online Accounts - Single sign-on framework for GNOME
==========================================================

%prep
%setup -q -n gnome-online-accounts-3.46.0
cd %{_builddir}/gnome-online-accounts-3.46.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663967542
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-online-accounts
cp %{_builddir}/gnome-online-accounts-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnome-online-accounts/21e40770dfa802576ee515345cef47ecedff6524 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
